### ISSUE TITLE
AttributeError: 'StarCraft2Env' object has no attribute 'get_true_avail_agent_actions'

### ISSUE THREAD

**Issue by DrPengZhe** [oxwhirl/smacv2#25]
I am a beginner in multi-agent reinforcement learning. Thank you for your contributions to multi-agent reinforcement learning. I encountered this error while using smacv2. It should be a simple error of missing function, but I can't seem to find this function in starcraft2.py.

Process Process-1:
Traceback (most recent call last):
  File "D:\anaconda3\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\anaconda3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\code\mappo-master\onpolicy\envs\env_wrappers.py", line 316, in shareworker
    ob, s_ob, available_actions = env.reset()
  File "D:\code\mappo-master\onpolicy\envs\starcraft2\SMACv2.py", line 25, in reset
    obs, state = super().reset()
  File "C:\Users\31315\smacv2\smacv2\env\starcraft2\wrapper.py", line 33, in reset
    return self.env.reset(reset_config)
  File "C:\Users\31315\smacv2\smacv2\env\starcraft2\starcraft2.py", line 582, in reset
    return self.get_obs(), self.get_state()
  File "C:\Users\31315\smacv2\smacv2\env\starcraft2\starcraft2.py", line 1728, in get_obs
    agents_obs[agent] = self.get_obs_agent(
  File "C:\Users\31315\smacv2\smacv2\env\starcraft2\starcraft2.py", line 1510, in get_obs_agent
    true_avail_actions = self.get_true_avail_agent_actions(agent_id)
AttributeError: 'StarCraft2Env' object has no attribute 'get_true_avail_agent_actions'

**Comment by benellis3** [comment]
Hi! Apologies for this -- the release of a new feature went wrong. We've fixed it now. Thanks for alerting us to this and please let us know if you have any further issues!

**Comment by benellis3** [comment]
Closing but reopen if you have more issues.
