### ISSUE TITLE
SMACv2 baseline QMIX in smacv2/RUNNING_EXPERIMENTS.md error

### ISSUE THREAD

**Issue by RupaliBhati** [oxwhirl/smacv2#38]
I'm trying to run SMACv2 baseline QMIX in smacv2/RUNNING_EXPERIMENTS.md. However, I keep running into this error:

```
Hello from the pygame community. https://www.pygame.org/contribute.html
[DEBUG 20:07:32] git.util Failed checking if running in CYGWIN due to: FileNotFoundError(2, 'No such file or directory')
[DEBUG 20:07:32] git.cmd Popen(['git', 'diff', '--cached', '--abbrev=40', '--full-index', '--raw'], cwd=/source, stdin=None, shell=False, universal_newlines=False)
Traceback (most recent call last):
  File "src/main.py", line 19, in <module>
    ex = Experiment("pymarl")
  File "/opt/conda/lib/python3.8/site-packages/sacred/experiment.py", line 119, in __init__
    super().__init__(
  File "/opt/conda/lib/python3.8/site-packages/sacred/ingredient.py", line 75, in __init__
    ) = gather_sources_and_dependencies(
  File "/opt/conda/lib/python3.8/site-packages/sacred/dependencies.py", line 728, in gather_sources_and_dependencies
    experiment_path, main = get_main_file(globs, save_git_info)
  File "/opt/conda/lib/python3.8/site-packages/sacred/dependencies.py", line 599, in get_main_file
    main = Source.create(globs.get("__file__"), save_git_info)
  File "/opt/conda/lib/python3.8/site-packages/sacred/dependencies.py", line 460, in create
    repo, commit, is_dirty = get_commit_if_possible(main_file, save_git_info)
  File "/opt/conda/lib/python3.8/site-packages/sacred/dependencies.py", line 440, in get_commit_if_possible
    is_dirty = repo.is_dirty()
  File "/opt/conda/lib/python3.8/site-packages/git/repo/base.py", line 820, in is_dirty
    if osp.isfile(self.index.path) and len(self.git.diff("--cached", *default_args)):
  File "/opt/conda/lib/python3.8/site-packages/git/cmd.py", line 736, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/git/cmd.py", line 1316, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/git/cmd.py", line 1111, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(129)
  cmdline: git diff --cached --abbrev=40 --full-index --raw
  stderr: 'Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>'
```

I've tried a few things but I'm not sure how to solve this. Is this a conda error or a git error? Any help on solving this would be much appreciated! Thank you.

**Comment by benellis3** [comment]
Hi! Thanks for raising an issue 😄. I will get to this when I am back from travelling next week. To help me can you tell me:
1) What command you were exactly running? 
2) What you had done before that?

To my mind this looks like a git error but I'm not sure.

**Comment by RupaliBhati** [comment]
For now, I ran the QMIX algorithm without the docker and it ran fine. I guess you can close this issue for now.
